apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-gin.fullname" . }}
  labels:
    {{- include "hello-gin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hello-gin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hello-gin.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: imgcred
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USERNAME
              value: "{{ .Values.username }}"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8080
              name: metrics
          livenessProbe:
            httpGet:
              path: "/api/v1/gin"
              port: http
          readinessProbe:
            httpGet:
              path: "/api/v1/gin"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
